### ISSUE TITLE
Empty line in the GFF crashes AGOUTI

### ISSUE THREAD

**Issue by svm-zhang** [svm-zhang/AGOUTI#10]
**_Paste Hannah's problem here:_**

Dear Mr. Zhang,
  I want to use AGOUTI to complete my genome assembly and the job broke down because of some reason that I don't know. Would you please help me to solve the problem ?
  Thank you so much!
   yours,
   hannah.
 
The command I used is :
 python agouti.py scaffold \
 -assembly monkfruit.contigs.fasta\
 -bam monkfruit_total.bam\
 -gff evm_monkfruit_mask.gff3\
 -outdir ./agouti1\
 -minMQ 20 -maxFracMM 0.05\
 -p monkfruit_agouti

 And the log file is :

  2017-05-03 18:50:41,425 - INFO - PARSE_ARGS PROGRESS - Assembly: /lustre1/deng_pkuhpc/hanxue/mecat/test_with_falcon_long_reads/monkfruit/monkfruit.contigs.fasta
2017-05-03 18:50:41,426 - INFO - PARSE_ARGS PROGRESS - Gene Model: /lustre1/deng_pkuhpc/hanxue/genome_annotation/EVM/do_evm_mask/evm_monkfruit_mask.gff3
2017-05-03 18:50:41,426 - INFO - PARSE_ARGS PROGRESS - Output directory: /lustre1/deng_pkuhpc/hanxue/scaffold/AGOUTI/agouti1
2017-05-03 18:50:41,426 - INFO - PARSE_ARGS PROGRESS - Output prefix: monkfruit_agouti
2017-05-03 18:50:41,427 - INFO - PARSE_ARGS PROGRESS - Minimum number of supports: 5
2017-05-03 18:50:41,427 - INFO - PARSE_ARGS PROGRESS - Length of gaps to fill between contigs: 1000
2017-05-03 18:50:41,429 - INFO - AGOUTI_SEQUENCE PROGRESS - [BEGIN] Reading the initial assembly
2017-05-03 18:50:43,520 - INFO - AGOUTI_SEQUENCE PROGRESS - 4128 sequences parsed
2017-05-03 18:50:43,520 - INFO - AGOUTI_SEQUENCE PROGRESS - The given assembly N50: 433684
2017-05-03 18:50:43,520 - INFO - AGOUTI_SEQUENCE PROGRESS - [DONE]
2017-05-03 18:50:43,546 - INFO - AGOUTI_GFF PROGRESS - [BEGIN] Getting gene models
Traceback (most recent call last):
  File "/lustre1/deng_pkuhpc/hanxue/bin/AGOUTI/agouti.py", line 288, in <module>
    main()
  File "/lustre1/deng_pkuhpc/hanxue/bin/AGOUTI/agouti.py", line 285, in main
    args.func(args)
  File "/lustre1/deng_pkuhpc/hanxue/bin/AGOUTI/agouti.py", line 201, in run_scaffolder
    dGFFs = agGFF.get_gene_models(gffFile, outDir, prefix, args.debug)
  File "/lustre1/deng_pkuhpc/hanxue/bin/AGOUTI/lib/agouti_gff.py", line 80, in get_gene_models
    if tmp_line[2] == "gene":
IndexError: list index out of range

**Comment by svm-zhang** [comment]
The bug fixes with commit [bab7574fb716d3bd498b9a2f94039b739952a314](https://github.com/svm-zhang/AGOUTI/commit/bab7574fb716d3bd498b9a2f94039b739952a314)
