### ISSUE TITLE
Multiple bugs encountered

### ISSUE THREAD

**Issue by pliang64** [svm-zhang/AGOUTI#15]
Hi Simo,

I wanted to try your tool, but encountered multiple issues as listed below. It would be great if you can provide a new working version.

Thanks,
Ping Liang

python ~/labbin/AGOUTI/agouti.py --version[pliang@cop33 AGOUTI]$ Traceback (most recent call last):
  File "/home/pliang/labbin/AGOUTI/agouti.py", line 20, in <module>
    from src import agouti_update as agUPDATE
  File "/gwork/lianglab/bin/AGOUTI/src/agouti_update.py", line 346
    print oriPath
                ^
SyntaxError: Missing parentheses in call to 'print'

[pliang@cop33 AGOUTI]$ 2017-10-23 12:00:12,293 - INFO - SHREDDER PROGRESS - [BEGIN] Shredding assembly
2017-10-23 12:00:12,338 - INFO - SHREDDER PROGRESS - # processed	| Current sequence ID	| Elapsed Time
Traceback (most recent call last):
  File "/home/pliang/labbin/AGOUTI/agouti.py", line 288, in <module>
    main()
  File "/home/pliang/labbin/AGOUTI/agouti.py", line 285, in main
    args.func(args)
  File "/home/pliang/labbin/AGOUTI/agouti.py", line 174, in run_shredder
    minGap, minCtgLen)
  File "/gwork/lianglab/bin/AGOUTI/src/agouti_shred.py", line 269, in agouti_shred_main
    dHeader2Intervals = shred_assembly(assemblyFile, breakerProgress, prefix, minGaps, minCtgLen)
  File "/gwork/lianglab/bin/AGOUTI/src/agouti_shred.py", line 292, in shred_assembly
    for header, seq in agSeq.read_fasta(assemblyFile):
  File "/gwork/lianglab/bin/AGOUTI/src/agouti_sequence.py", line 56, in read_fasta
    header = header.next()[1:].strip().split()[0]
AttributeError: 'itertools._grouper' object has no attribute 'next'

**Comment by svm-zhang** [comment]
Hello Ping,

Thanks for using AGOUTI.

From what I see here, are you using Python 3?

Simo

**Comment by svm-zhang** [comment]
Close now. Reopen if issue persists.
