### ISSUE TITLE
Start index must be 1 or larger; GFF is 1-based

### ISSUE THREAD

**Issue by TakashiKoyama** [svm-zhang/AGOUTI#2]
Hi,

I appreciate you to distribute such a nice tool.
I have a problem with viewing the GFF file produced by AGOUTI.

To check gene structure on IGV, I have first made sorted GFF.

```
$ igvtools sort platanus_k35.sorted.cleaned.nsorted.k3.agouti.gff platanus_k35.sorted.cleaned.nsorted.k3.agouti.sorted.gff
```

then, indexed

```
$ igvtools index platanus_k35.sorted.cleaned.nsorted.k3.agouti.sorted.gff
```

and got error

```
ERROR [2016-01-19 20:03:26,381]  [IgvTools.java:250] [main]  Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k3_scaf_12  AGOUTI  gene    -2  1679    .   .   .   ID=AGOUTI_Merged_gene_14;MERGE_FROM_GENES=scaffold361749_cov106_AGOUTI_fake_0,scaffold305397_cov53_AGOUTI_fake_0;MERGE_FROM_CONTIGS=scaffold361749_cov106,scaffold305397_cov53

  Start index must be 1 or larger; GFF is 1-based
org.broad.igv.exceptions.ParserException: Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k3_scaf_12  AGOUTI  gene    -2  1679    .   .   .   ID=AGOUTI_Merged_gene_14;MERGE_FROM_GENES=scaffold361749_cov106_AGOUTI_fake_0,scaffold305397_cov53_AGOUTI_fake_0;MERGE_FROM_CONTIGS=scaffold361749_cov106,scaffold305397_cov53

  Start index must be 1 or larger; GFF is 1-based
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:241)
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:67)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
    at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:502)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:464)
    at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:338)
    at htsjdk.tribble.index.IndexFactory.createLinearIndex(IndexFactory.java:223)
    at org.broad.igv.tools.IgvTools.createTribbleIndex(IgvTools.java:1016)
    at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:968)
    at org.broad.igv.tools.IgvTools.run(IgvTools.java:379)
    at org.broad.igv.tools.IgvTools.main(IgvTools.java:245)
Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k3_scaf_12  AGOUTI  gene    -2  1679    .   .   .   ID=AGOUTI_Merged_gene_14;MERGE_FROM_GENES=scaffold361749_cov106_AGOUTI_fake_0,scaffold305397_cov53_AGOUTI_fake_0;MERGE_FROM_CONTIGS=scaffold361749_cov106,scaffold305397_cov53

  Start index must be 1 or larger; GFF is 1-based
org.broad.igv.exceptions.ParserException: Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k3_scaf_12  AGOUTI  gene    -2  1679    .   .   .   ID=AGOUTI_Merged_gene_14;MERGE_FROM_GENES=scaffold361749_cov106_AGOUTI_fake_0,scaffold305397_cov53_AGOUTI_fake_0;MERGE_FROM_CONTIGS=scaffold361749_cov106,scaffold305397_cov53

  Start index must be 1 or larger; GFF is 1-based
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:241)
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:67)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
    at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:502)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:464)
    at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:338)
    at htsjdk.tribble.index.IndexFactory.createLinearIndex(IndexFactory.java:223)
    at org.broad.igv.tools.IgvTools.createTribbleIndex(IgvTools.java:1016)
    at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:968)
    at org.broad.igv.tools.IgvTools.run(IgvTools.java:379)
    at org.broad.igv.tools.IgvTools.main(IgvTools.java:245)
```

According to error message, I checked my GFF and found a lot of '-2'.
Could you tell me how can I fix this problem?

Thank you for your kind helps.

Takashi

**Comment by svm-zhang** [comment]
Hi Takashi,

Thanks for using AGOUTI.

It looks like there is a bug when gene models got merged. The coordinates were not updated in a right way. I have some idea where it might go wrong. Please give me a bit time to look into this.

Thanks,
Simo

**Comment by TakashiKoyama** [comment]
Hi Simo,

Thank you for your reply.
OK. This is quite nice tool. Please let me know if you fix this problem.

Thanks,
Takashi

**Comment by svm-zhang** [comment]
Hi Takashi,

You are very welcome!

I think I figured out why. Let me try to explain using an example. Let's say the leftmost positions of a read is mapped to 5261 on a contig of length 5330, and the alignment length is 70. The rightmost position can then be derived as 5261+70-1=5330. I coded this wrong as 5261+70=5331, which is one base pair beyond the length of this contig. Also The leftmost position in SAM is 1-based, which I treated as 0-based (because I thought I read directly from BAM...). Together this gives two base pairs beyond the boundary of the contig, which in turn gave you gene models starting at -2.

I released a new version: v0.3.1. Could you please pull out this version and try again? And please keep me post it on whether it works out.

Thank you for reporting this bug :)

Simo

**Comment by TakashiKoyama** [comment]
Hi Simo,

Thank you for fixing the bug quickly. 
It works fine with my data and I think the problem is fixed.
But I found other problems.
1. The fasta file agouti produced has header in which scaffold name, length and original scaffold names are separated by '|'. IGV can't seem to recognize this as separator and so the produced header names do not match with the name in gff.
   I could replace '|' with space by sed command but I think it would be helpful if you change separator.
2. IGV does not display exon-intron structure from gff agouti produced. Unfortunately I am not familiar with gff format and I cannot figure out what is problem. For your information, I will show you a part of my gff from agouti and augustus respectively.

**gff from agouti**

```
##gff-version3
# This output was generated with AGOUTI (version 0.1)
# start gene g23520
platanus_k35.sorted.cleaned.nsorted.k3_scaf_1   AGOUTI  gene    1   1294    .   .   .   ID=AGOUTI_Merged_gene_1;MERGE_FROM_GENES=scaffold145281_cov18_AGOUTI_fake_0;MERGE_FROM_CONTIGS=scaffold145281_cov18,scaffold289495_cov27
platanus_k35.sorted.cleaned.nsorted.k3_scaf_1   AGOUTI  exon    1   100 .   .   .   ID=AGOUTI_Merged_gene_1.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_1   AGOUTI  exon    1101    1294    .   .   .   ID=AGOUTI_Merged_gene_1.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    15092   15468   .   +   .   ID=g86
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    15092   15196   .   +   .   ID=g86.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    15346   15468   .   +   .   ID=g86.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    26142   27833   .   -   .   ID=g85
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    26142   27833   .   -   .   ID=g85.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    33928   34485   .   +   .   ID=g84
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    33928   33942   .   +   .   ID=g84.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    34194   34350   .   +   .   ID=g84.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    34412   34485   .   +   .   ID=g84.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    42606   43230   .   +   .   ID=g83
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    42606   42652   .   +   .   ID=g83.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    42751   42866   .   +   .   ID=g83.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    43178   43230   .   +   .   ID=g83.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    49425   52344   .   -   .   ID=g82
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    49425   49586   .   -   .   ID=g82.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    51640   51735   .   -   .   ID=g82.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    52303   52344   .   -   .   ID=g82.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    53978   56782   .   -   .   ID=g81
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    53978   54076   .   -   .   ID=g81.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    55235   55399   .   -   .   ID=g81.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    56243   56275   .   -   .   ID=g81.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    56747   56782   .   -   .   ID=g81.exon
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    gene    74542   76766   .   -   .   ID=g80
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS    exon    74542   75306   .   -   .   ID=g80.exon
```

**gff from augustus**

```
##gff-version 3
# This output was generated with AUGUSTUS (version 3.2.1).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
# O. Keller, S. KÃ¶nig, L. Gerischer and L. Romoth.
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# No extrinsic information on sequences given.
# Initialising the parameters using config directory /home/samba/public/software/augustus-3.2.1/config/ ...
# yellowtail_bycegma version. Using default transition matrix.
# admissible start codons and their probabilities: ATG(1), CTG(0), TTG(0)
# Looks like platanus_k35_gapClosed.substituted.fixfasta.fasta.masked.masked is in fasta format.
# We have hints for 0 sequences and for 0 of the sequences in the input set.
#
# ----- prediction on sequence number 1 (length = 1154345, name = SquSD_finalassembly150907) -----
#
# Predicted genes for sequence number 1 on both strands
# start gene g1
scaffold2_cov39 AUGUSTUS    gene    1420    2935    0.84    +   .   ID=g31458
scaffold2_cov39 AUGUSTUS    transcript  1420    2935    0.84    +   .   ID=g31458.t1;Parent=g31458
scaffold2_cov39 AUGUSTUS    start_codon 1420    1422    .   +   0   Parent=g31458.t1
scaffold2_cov39 AUGUSTUS    CDS 1420    1492    0.94    +   0   ID=g31458.t1.cds;Parent=g31458.t1
scaffold2_cov39 AUGUSTUS    intron  1493    2409    0.94    +   .   Parent=g31458.t1
scaffold2_cov39 AUGUSTUS    CDS 2410    2596    0.97    +   2   ID=g31458.t1.cds;Parent=g31458.t1
scaffold2_cov39 AUGUSTUS    intron  2597    2847    0.9 +   .   Parent=g31458.t1
scaffold2_cov39 AUGUSTUS    CDS 2848    2935    0.9 +   1   ID=g31458.t1.cds;Parent=g31458.t1
scaffold2_cov39 AUGUSTUS    stop_codon  2933    2935    .   +   0   Parent=g31458.t1
scaffold3_cov51 AUGUSTUS    gene    14898   15140   0.78    +   .   ID=g11991
scaffold3_cov51 AUGUSTUS    transcript  14898   15140   0.78    +   .   ID=g11991.t1;Parent=g11991
scaffold3_cov51 AUGUSTUS    start_codon 14898   14900   .   +   0   Parent=g11991.t1
scaffold3_cov51 AUGUSTUS    CDS 14898   15140   0.78    +   0   ID=g11991.t1.cds;Parent=g11991.t1
scaffold3_cov51 AUGUSTUS    stop_codon  15138   15140   .   +   0   Parent=g11991.t1
scaffold3_cov51 AUGUSTUS    gene    26107   34467   0.48    -   .   ID=g11992
scaffold3_cov51 AUGUSTUS    transcript  26107   34467   0.48    -   .   ID=g11992.t1;Parent=g11992
scaffold3_cov51 AUGUSTUS    stop_codon  26107   26109   .   -   0   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 26107   26133   0.82    -   0   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    intron  26134   26250   0.82    -   .   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 26251   26425   0.92    -   1   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    intron  26426   26782   0.99    -   .   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 26783   26995   0.99    -   1   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    intron  26996   30476   0.96    -   .   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 30477   30613   0.99    -   0   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    intron  30614   31339   1   -   .   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 31340   31460   1   -   1   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    intron  31461   32544   0.99    -   .   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 32545   32791   1   -   2   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    intron  32792   34439   0.68    -   .   Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    CDS 34440   34467   0.68    -   0   ID=g11992.t1.cds;Parent=g11992.t1
scaffold3_cov51 AUGUSTUS    start_codon 34465   34467   .   -   0   Parent=g11992.t1
scaffold11_cov44    AUGUSTUS    gene    12889   15307   0.99    -   .   ID=g14783
```

I really appreciate all of your helps.

Takashi

**Comment by TakashiKoyama** [comment]
Hi Simo,

I have found another problem.
If I execute agouti with '-k 3', agouti works fine. But if with '-k 2', igvtools index produced error.
The error message below still find start position with '-'.

```
$ igvtools index platanus_k35.sorted.cleaned.nsorted.k2.agouti.sorted.gff
ERROR [2016-01-21 15:27:40,271]  [IgvTools.java:250] [main]  Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k2_scaf_3551    AGOUTI  exon    -13239  -13144  .   -   .   ID=AGOUTI_Merged_gene_4067.exon

  Start index must be 1 or larger; GFF is 1-based
org.broad.igv.exceptions.ParserException: Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k2_scaf_3551    AGOUTI  exon    -13239  -13144  .   -   .   ID=AGOUTI_Merged_gene_4067.exon

  Start index must be 1 or larger; GFF is 1-based
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:241)
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:67)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
    at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:502)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:464)
    at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:338)
    at htsjdk.tribble.index.IndexFactory.createLinearIndex(IndexFactory.java:223)
    at org.broad.igv.tools.IgvTools.createTribbleIndex(IgvTools.java:1016)
    at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:968)
    at org.broad.igv.tools.IgvTools.run(IgvTools.java:379)
    at org.broad.igv.tools.IgvTools.main(IgvTools.java:245)
Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k2_scaf_3551    AGOUTI  exon    -13239  -13144  .   -   .   ID=AGOUTI_Merged_gene_4067.exon

  Start index must be 1 or larger; GFF is 1-based
org.broad.igv.exceptions.ParserException: Failed to parse line -1:
    platanus_k35.sorted.cleaned.nsorted.k2_scaf_3551    AGOUTI  exon    -13239  -13144  .   -   .   ID=AGOUTI_Merged_gene_4067.exon

  Start index must be 1 or larger; GFF is 1-based
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:241)
    at org.broad.igv.feature.tribble.GFFCodec.decode(GFFCodec.java:67)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
    at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:502)
    at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:464)
    at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:338)
    at htsjdk.tribble.index.IndexFactory.createLinearIndex(IndexFactory.java:223)
    at org.broad.igv.tools.IgvTools.createTribbleIndex(IgvTools.java:1016)
    at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:968)
    at org.broad.igv.tools.IgvTools.run(IgvTools.java:379)
    at org.broad.igv.tools.IgvTools.main(IgvTools.java:245)
```

Thanks,
Takashi

**Comment by svm-zhang** [comment]
For your first question:

The fasta file agouti produced has header in which scaffold name, length and original scaffold names are separated by '|'. IGV can't seem to recognize this as separator and so the produced header names do not match with the name in gff.
I could replace '|' with space by sed command but I think it would be helpful if you change separator.

Could you please give me an example both the seq name generated by AGOUTI and how IGV interpreted that. And also what did you replaced with that IGV recognized. 

Thanks!

**Comment by svm-zhang** [comment]
I made a new patch (I have not yet released a new version; you can use git pull to get the patch I believe) with the following fixes:
1. added an extra space before `|`: `>80k.run10.n2_scaf_1 |21038bp |IV_664,IV_665,IV_666`. IGV now should load the sequences correctly.
2. reformatted the final GFF file to be more standard. IGV now should be able to show the exon/intron boundaries. I ran igvtools sort on my GFF files before feeding them to IGV.
3. fixed a bug that did not update the coordinates of gene models correctly. But I am not sure if this can help with the last error (i.e. negative starting position) you saw. If not, could you please send all the debug files generated by AGOUTI to simozhan@indiana.edu? We then go from there. To generate debug files, simply specify -debug option.

Thanks again for your patience and help!

**Comment by TakashiKoyama** [comment]
Hi, Simo
- The sequence name is now correctly loaded by IGV. Thanks!
- IGV still do not display exon-intron structure from revised gff. For example, gene structure of g73 in the revised gff is as below.

```
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        gene    187581  195864  .       +       .       ID=g73
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        mRNA    187581  195864  .       +       .       ID=g73.mRNA;Parent=g73
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    187581  187704  .       +       .       ID=g73.exon.1;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    188885  189037  .       +       .       ID=g73.exon.2;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    189898  190099  .       +       .       ID=g73.exon.3;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    191122  191262  .       +       .       ID=g73.exon.4;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    191617  191722  .       +       .       ID=g73.exon.5;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    192345  192442  .       +       .       ID=g73.exon.6;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    193056  193176  .       +       .       ID=g73.exon.7;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    194353  194582  .       +       .       ID=g73.exon.8;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        exon    195825  195864  .       +       .       ID=g73.exon.9;Parent=g73.mRNA
```

And IGV display attached view.
![igv_snapshot](https://cloud.githubusercontent.com/assets/11766897/12502445/1e86f222-c10c-11e5-9140-6aff33dca710.png)

However, if I changed 'exon' in the revised gff to 'CDS' as below,

```
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        gene    187581  195864  .       +       .       ID=g73
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        mRNA    187581  195864  .       +       .       ID=g73.mRNA;Parent=g73
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     187581  187704  .       +       .       ID=g73.exon.1;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     188885  189037  .       +       .       ID=g73.exon.2;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     189898  190099  .       +       .       ID=g73.exon.3;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     191122  191262  .       +       .       ID=g73.exon.4;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     191617  191722  .       +       .       ID=g73.exon.5;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     192345  192442  .       +       .       ID=g73.exon.6;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     193056  193176  .       +       .       ID=g73.exon.7;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     194353  194582  .       +       .       ID=g73.exon.8;Parent=g73.mRNA
platanus_k35.sorted.cleaned.nsorted.k3_scaf_2   AUGUSTUS        CDS     195825  195864  .       +       .       ID=g73.exon.9;Parent=g73.mRNA
```

IGV display gene structure correctly:)
![igv_snapshot2](https://cloud.githubusercontent.com/assets/11766897/12502559/8d933742-c10d-11e5-8eb1-c987dcdb7feb.png)
So, could you change 'exon' in the script to 'CDS'?
- I still have error if I execute agouti.py with '-k 2'. I will send my debug files. I usually use hotmail. If you have not received my mail, please check spam mail directory.

Thank you for your kind helps!

Takashi

**Comment by svm-zhang** [comment]
Can I ask you what version of IGV you were using. I tested on the lastest 2.3. This version does not show exon/intron structures automatically. You need to specify `Expanded` view from the pop-up menu by right-clicking your track.  Here is a screenshot of my GFF in the IGV using `exon` as feature with `Expanded` view.

![igv_exon](https://cloud.githubusercontent.com/assets/3883886/12513328/53600360-c0eb-11e5-9514-420468295c14.jpg)

Without `Expanded`, it looks like this:

![igv_exon_collapsed](https://cloud.githubusercontent.com/assets/3883886/12513416/abd39048-c0eb-11e5-9c28-2facca5ae48a.jpg)

Could you please give this a try? If still not working, let me think about using `CDS` instead of `exon`, because some exons are additional evidences from RNA-seq mapping. In other words, they are not necessarily part of coding frames.

Thank your for bearing with me here a bit longer.

**Comment by TakashiKoyama** [comment]
Hi Simo,

Ah, I didn't know that. I finally got exon-intron view! Thanks!
![igv_snapshot3](https://cloud.githubusercontent.com/assets/11766897/12514344/4b2f312c-c166-11e5-8272-ffc677b126d9.png)

Takashi

**Comment by svm-zhang** [comment]
WooHoooo! Great!

**Comment by TakashiKoyama** [comment]
Hi Simo,

I tried the revised version of AGOUTI.
I found one syntax error.

```
Traceback (most recent call last):
  File "/home/koyama/Downloads/AGOUTI/agouti.py", line 20, in <module>
    from src import agouti_scaffolding as agSCAFF
  File "/home/koyama/Downloads/AGOUTI/src/agouti_scaffolding.py", line 408
    elif preSensePair == "++" and curSensePair == "--" or curSensePair == "-+"):
                                                                              ^
```

So I changed

```
elif preSensePair == "++" and curSensePair == "--" or curSensePair == "-+"):
```

to 

```
elif preSensePair == "++" and (curSensePair == "--" or curSensePair == "-+"):
```

And AGOUTI produced gff which can be perfectly parsed by igvtools!
Yeah! You are amazing!!
Thank you so much!

Takashi

**Comment by svm-zhang** [comment]
Aha, missing parenthesis... Thanks!

Just fixed!

I am gonna close this issue now. Any further problems you have, please go ahead create a new thread.

Simo
