### ISSUE TITLE
Recover_untouched_sequences ValueError

### ISSUE THREAD

**Issue by gh-ahardin** [svm-zhang/AGOUTI#5]
Hi! I'm trying this on a assembly created with meraculous and previously annotated with AGUSTUS. Things seem to be going well but I'm getting this error:

 2016-07-02 11:50:35,136 - INFO - AGOUTI_PATH PROGRESS - [BEGIN] Recovring original scaffolding
Traceback (most recent call last):
  File "/home/aaron/bin/AGOUTI/agouti.py", line 286, in <module>
    main()
  File "/home/aaron/bin/AGOUTI/agouti.py", line 283, in main
    args.func(args)
  File "/home/aaron/bin/AGOUTI/agouti.py", line 220, in run_scaffolder
    prefix)
  File "/home/aaron/bin/AGOUTI/src/agouti_path.py", line 41, in agouti_path_main
    agPathDebug)
  File "/home/aaron/bin/AGOUTI/src/agouti_path.py", line 77, in recover_untouched_sequences
    preCtgIndex = int(preCtg.split('_')[-1])
ValueError: invalid literal for int() with base 10: 'Scaffold421951'

**Comment by svm-zhang** [comment]
Hello!

Thanks for using AGOUTI. 

Could you please give little bit more information on what you have done?

And I just made an patch one hour ago. Could you please pull that down and try again. If the error is still there, let me understand your case a bit more and we go from there.

Simo

**Comment by gh-ahardin** [comment]
Thanks! The patch solved the error.

**Comment by svm-zhang** [comment]
Glad to hear it worked out for you.
